"""First commit

Revision ID: 5f098b5aaa30
Revises: 820a46e5d7c9
Create Date: 2023-01-24 14:58:49.730204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f098b5aaa30'
down_revision = '820a46e5d7c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
